# Generated by Django 2.1.4 on 2019-02-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotWord',
            new_name='NonWord',
        ),
    ]
