# Generated by Django 2.1.4 on 2019-10-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20191012_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='alphabetic_order',
            field=models.ForeignKey(on_delete='protect', related_name='d_set', to='base.AlphabeticOrder'),
        ),
        migrations.AlterField(
            model_name='language',
            name='case_set',
            field=models.ForeignKey(default=1, on_delete='protect', related_name='b_set', to='base.CaseSet'),
        ),
        migrations.AlterField(
            model_name='language',
            name='period_sep',
            field=models.ForeignKey(on_delete='protect', related_name='c_set', to='base.TokenRegexp'),
        ),
        migrations.AlterField(
            model_name='language',
            name='token_regexp_set',
            field=models.ForeignKey(on_delete='protect', related_name='a_set', to='base.TokenRegexpSet'),
        ),
    ]
