# Generated by Django 2.1.4 on 2019-11-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FusedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.CharField(db_index=True, editable=False, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='FusedWordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('fused_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.FusedWord')),
            ],
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FusionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FusionRuleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('fusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Fusion')),
                ('fusion_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.FusionRule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Inflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_entry', models.BooleanField(default=False)),
                ('description_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description')),
            ],
            options={
                'ordering': ['regsub'],
            },
        ),
        migrations.CreateModel(
            name='Paradigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('inflections', models.ManyToManyField(blank=True, to='morphology.Inflection')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('bg_color', models.CharField(default='#ffff00', max_length=20)),
                ('fg_color', models.CharField(default='#000000', max_length=20)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegexpReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=1024)),
                ('replacement', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['pattern', 'replacement'],
            },
        ),
        migrations.CreateModel(
            name='RegexpReverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=1024)),
                ('replacement', models.CharField(max_length=1024)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reverse', to='morphology.RegexpReplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=1024)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech')),
            ],
            options={
                'ordering': ['root'],
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.CharField(db_index=True, editable=False, max_length=1024)),
                ('derivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Derivation')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Root')),
            ],
            options={
                'ordering': ['cache'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemaArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.TemaArgument')),
            ],
            options={
                'ordering': ['argument', 'value'],
            },
        ),
        migrations.CreateModel(
            name='TemaEntryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.TemaEntry')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Tema')),
            ],
            options={
                'ordering': ['entry'],
            },
        ),
        migrations.CreateModel(
            name='TemaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.CharField(db_index=True, editable=False, max_length=1024)),
                ('inflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Inflection')),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Stem')),
            ],
            options={
                'ordering': ['cache'],
            },
        ),
        migrations.AddField(
            model_name='temaentry',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.TemaValue'),
        ),
        migrations.AddField(
            model_name='root',
            name='tema_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Tema'),
        ),
        migrations.AddField(
            model_name='paradigma',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AddField(
            model_name='inflection',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AddField(
            model_name='fusionrule',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AddField(
            model_name='fusionrule',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AddField(
            model_name='fusionrule',
            name='tema_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Tema'),
        ),
        migrations.AddField(
            model_name='fusedwordrelation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Word'),
        ),
        migrations.AddField(
            model_name='fusedword',
            name='fusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Fusion'),
        ),
        migrations.AddField(
            model_name='derivation',
            name='paradigma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Paradigma'),
        ),
        migrations.AddField(
            model_name='derivation',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AddField(
            model_name='derivation',
            name='root_part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AddField(
            model_name='derivation',
            name='tema_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.TemaEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='temaentry',
            unique_together={('argument', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='root',
            unique_together={('language', 'root', 'tema_obj', 'part_of_speech')},
        ),
    ]
