# Generated by Django 2.1.4 on 2019-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, editable=False, max_length=1024)),
                ('description', models.CharField(editable=False, max_length=8000)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.AddField(
            model_name='fusedword',
            name='description',
            field=models.CharField(default='{}', editable=False, max_length=8000),
            preserve_default=False,
        ),
    ]
