# Generated by Django 2.1.4 on 2019-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0002_auto_20190214_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCache',
        ),
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.CharField(default='{}', editable=False, max_length=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, default='{}', editable=False, max_length=1024),
            preserve_default=False,
        ),
    ]
