# Generated by Django 2.1.4 on 2019-02-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0003_auto_20190214_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fusedword',
            old_name='word',
            new_name='cache',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='cache',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='description',
            new_name='cache_description',
        ),
        migrations.RemoveField(
            model_name='fusedword',
            name='description',
        ),
    ]
