# Generated by Django 2.1.4 on 2019-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0004_auto_20190214_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fusion',
            name='language',
            field=models.ForeignKey(on_delete='cascade', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='paradigma',
            name='language',
            field=models.ForeignKey(on_delete='cascade', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='root',
            name='language',
            field=models.ForeignKey(on_delete='cascade', to='languages.Language'),
        ),
    ]
