# Generated by Django 2.1.4 on 2019-02-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0005_auto_20190214_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cache_part_of_speech',
            field=models.CharField(db_index=True, default='', editable=False, max_length=1024),
            preserve_default=False,
        ),
    ]
