# Generated by Django 2.1.4 on 2019-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0007_auto_20190216_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradigmainflection',
            name='inflection',
        ),
        migrations.RemoveField(
            model_name='paradigmainflection',
            name='paradigma',
        ),
        migrations.AddField(
            model_name='paradigma',
            name='inflections',
            field=models.ManyToManyField(blank=True, to='morphology.Paradigma'),
        ),
        migrations.DeleteModel(
            name='ParadigmaInflection',
        ),
    ]
