# Generated by Django 2.1.4 on 2019-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0008_auto_20190216_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradigma',
            name='inflections',
            field=models.ManyToManyField(blank=True, to='morphology.Inflection'),
        ),
    ]
