# Generated by Django 2.1.4 on 2019-02-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0009_auto_20190216_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='cache_description',
        ),
        migrations.RemoveField(
            model_name='word',
            name='cache_part_of_speech',
        ),
    ]
