# Generated by Django 2.1.4 on 2019-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0010_auto_20190216_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='bg_color',
            field=models.CharField(default='#ffff00', max_length=20),
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='fg_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
