# Generated by Django 2.1.4 on 2019-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190214_1751'),
        ('morphology', '0011_auto_20190216_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivation',
            name='language',
            field=models.ForeignKey(default=1, on_delete='cascade', to='languages.Language'),
            preserve_default=False,
        ),
    ]
