# Generated by Django 2.1.4 on 2019-02-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0013_auto_20190216_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FusionWordRelation',
            new_name='FusedWordRelation',
        ),
        migrations.AlterModelOptions(
            name='fusionrulerelation',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['cache']},
        ),
    ]
