# Generated by Django 2.1.2 on 2019-02-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0014_auto_20190217_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derivation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['name']},
        ),
    ]
