# Generated by Django 2.1.4 on 2019-02-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0015_auto_20190219_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paradigma',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regexpreplacement',
            options={'ordering': ['replacement']},
        ),
    ]
