# Generated by Django 2.1.4 on 2019-10-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0016_auto_20190219_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fusion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fusionrule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inflection',
            options={'ordering': ['regsub']},
        ),
        migrations.AlterModelOptions(
            name='partofspeech',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regexpreplacement',
            options={'ordering': ['pattern', 'replacement']},
        ),
        migrations.AlterModelOptions(
            name='temaargument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='temavalue',
            options={'ordering': ['name']},
        ),
    ]
