# Generated by Django 2.2.5 on 2019-10-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0018_auto_20191021_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='stem',
            name='cache',
            field=models.CharField(db_index=True, default='', editable=False, max_length=1024),
            preserve_default=False,
        ),
    ]
