# Generated by Django 2.1.4 on 2019-10-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20191021_0715'),
        ('languages', '0004_auto_20191012_1454'),
        ('morphology', '0019_stem_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stem',
            options={'ordering': ['cache']},
        ),
        migrations.AlterUniqueTogether(
            name='root',
            unique_together={('language', 'root', 'tema_obj', 'part_of_speech', 'description_obj')},
        ),
    ]
