# Generated by Django 2.1.4 on 2019-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0020_auto_20191021_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexpReverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=1024)),
                ('replacement', models.CharField(max_length=1024)),
                ('regexp', models.OneToOneField(on_delete='cascade', to='morphology.RegexpReplacement')),
            ],
        ),
        migrations.AlterField(
            model_name='derivation',
            name='description_obj',
            field=models.ForeignKey(on_delete='protect', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='language',
            field=models.ForeignKey(on_delete='protect', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='paradigma',
            field=models.ForeignKey(on_delete='protect', to='morphology.Paradigma'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='regsub',
            field=models.ForeignKey(on_delete='protect', to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='root_description_obj',
            field=models.ForeignKey(on_delete='protect', related_name='root_derivation_set', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='root_part_of_speech',
            field=models.ForeignKey(on_delete='protect', to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='tema_obj',
            field=models.ForeignKey(on_delete='protect', to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='language',
            field=models.ForeignKey(on_delete='protect', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='description_obj',
            field=models.ForeignKey(on_delete='protect', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='part_of_speech',
            field=models.ForeignKey(on_delete='protect', to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='regsub',
            field=models.ForeignKey(on_delete='protect', to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='tema_obj',
            field=models.ForeignKey(on_delete='protect', to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='inflection',
            name='description_obj',
            field=models.ForeignKey(on_delete='protect', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='inflection',
            name='regsub',
            field=models.ForeignKey(on_delete='protect', to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='paradigma',
            name='language',
            field=models.ForeignKey(on_delete='protect', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='paradigma',
            name='part_of_speech',
            field=models.ForeignKey(on_delete='protect', to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='root',
            name='description_obj',
            field=models.ForeignKey(on_delete='protect', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='root',
            name='language',
            field=models.ForeignKey(on_delete='protect', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='root',
            name='part_of_speech',
            field=models.ForeignKey(on_delete='protect', to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='root',
            name='tema_obj',
            field=models.ForeignKey(on_delete='protect', to='morphology.Tema'),
        ),
    ]
