# Generated by Django 2.1.4 on 2019-10-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0021_auto_20191026_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regexpreverse',
            old_name='regexp',
            new_name='target',
        ),
    ]
