# Generated by Django 2.1.4 on 2019-10-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0023_auto_20191026_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivation',
            name='description_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='paradigma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Paradigma'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='root_description_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_derivation_set', to='base.Description'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='root_part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='derivation',
            name='tema_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='fusedword',
            name='fusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Fusion'),
        ),
        migrations.AlterField(
            model_name='fusedwordrelation',
            name='fused_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.FusedWord'),
        ),
        migrations.AlterField(
            model_name='fusedwordrelation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Word'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='description_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='fusionrule',
            name='tema_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='fusionrulerelation',
            name='fusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Fusion'),
        ),
        migrations.AlterField(
            model_name='fusionrulerelation',
            name='fusion_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.FusionRule'),
        ),
        migrations.AlterField(
            model_name='inflection',
            name='description_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description'),
        ),
        migrations.AlterField(
            model_name='inflection',
            name='regsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='paradigma',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='paradigma',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='regexpreverse',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reverse', to='morphology.RegexpReplacement'),
        ),
        migrations.AlterField(
            model_name='root',
            name='description_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Description'),
        ),
        migrations.AlterField(
            model_name='root',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='root',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='root',
            name='tema_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='derivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Derivation'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Root'),
        ),
        migrations.AlterField(
            model_name='temaentry',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.TemaArgument'),
        ),
        migrations.AlterField(
            model_name='temaentry',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Tema'),
        ),
        migrations.AlterField(
            model_name='temaentry',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.TemaValue'),
        ),
        migrations.AlterField(
            model_name='word',
            name='inflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Inflection'),
        ),
        migrations.AlterField(
            model_name='word',
            name='stem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Stem'),
        ),
    ]
