# Generated by Django 2.1.4 on 2019-11-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0025_temaentryrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaentry',
            name='tema',
        ),
    ]
