# Generated by Django 2.1.4 on 2019-11-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20191026_0545'),
        ('morphology', '0028_remove_derivation_root_description_obj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='root',
            unique_together={('language', 'root', 'tema_obj', 'part_of_speech')},
        ),
    ]
