# Generated by Django 2.1.4 on 2019-11-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0029_auto_20191102_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='description_obj',
        ),
    ]
