# Generated by Django 2.1.4 on 2019-11-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0031_derivation_tema_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivation',
            name='tema_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='morphology.TemaEntry'),
        ),
    ]
