# Generated by Django 2.1.4 on 2019-11-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0032_auto_20191102_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivation',
            name='tema_obj',
        ),
    ]
