# Generated by Django 2.1.4 on 2019-11-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0005_auto_20191026_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete='protect', to='languages.Language')),
            ],
            options={
                'verbose_name_plural': 'corpora',
            },
        ),
        migrations.CreateModel(
            name='MetaDataArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetaDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('argument', models.ForeignKey(on_delete='protect', to='corpora.MetaDataArgument')),
            ],
            options={
                'ordering': ['argument', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('label', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WDConcorso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('tag', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Wd concorsi',
            },
        ),
        migrations.CreateModel(
            name='WDForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('wd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WDAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpora.Author')),
                ('wd_id', models.IntegerField()),
            ],
            bases=('corpora.author',),
        ),
        migrations.CreateModel(
            name='WDText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpora.Text')),
                ('wd_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('concorso', models.ForeignKey(on_delete='protect', to='corpora.WDConcorso')),
                ('forum', models.ForeignKey(on_delete='protect', to='corpora.WDForum')),
            ],
            bases=('corpora.text',),
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete='protect', to='corpora.Author'),
        ),
        migrations.AddField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(on_delete='protect', to='corpora.Corpus'),
        ),
        migrations.AddField(
            model_name='metadataentry',
            name='text',
            field=models.ForeignKey(on_delete='cascade', to='corpora.Text'),
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('corpus', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='metadataentry',
            unique_together={('text', 'argument')},
        ),
    ]
