# Generated by Django 2.1.4 on 2019-02-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_language_notword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.ForeignKey(on_delete='cascade', to='base.Language')),
            ],
            options={
                'verbose_name_plural': 'corpora',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WDConcorso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('tag', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Wd concorsi',
            },
        ),
        migrations.CreateModel(
            name='WDForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('wd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WDAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpora.Author')),
                ('wd_id', models.IntegerField()),
            ],
            bases=('corpora.author',),
        ),
        migrations.CreateModel(
            name='WDText',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpora.Text')),
                ('wd_id', models.IntegerField()),
                ('concorso', models.ForeignKey(on_delete='cascade', to='corpora.WDConcorso')),
                ('forum', models.ForeignKey(on_delete='cascade', to='corpora.WDForum')),
            ],
            bases=('corpora.text',),
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete='cascade', to='corpora.Author'),
        ),
        migrations.AddField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(on_delete='cascade', to='corpora.Corpus'),
        ),
    ]
