# Generated by Django 2.1.2 on 2019-02-12 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='wdtext',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
