# Generated by Django 2.1.2 on 2019-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_auto_20190212_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='language',
            field=models.ForeignKey(on_delete='cascade', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
