# Generated by Django 2.2.5 on 2019-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_auto_20190218_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaDataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.ForeignKey(on_delete='cascade', to='corpora.MetaDataArgument')),
                ('text', models.ForeignKey(on_delete='cascade', to='corpora.Text')),
                ('value', models.ForeignKey(on_delete='cascade', to='corpora.MetaDataValue')),
            ],
            options={
                'ordering': ['argument', 'value'],
            },
        ),
    ]
