# Generated by Django 2.1.4 on 2019-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_auto_20190214_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
