# Generated by Django 2.2.5 on 2019-10-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0004_metadataargument_metadataentry_metadatavalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataentry',
            name='value',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='MetaDataValue',
        ),
    ]
