# Generated by Django 2.2.5 on 2019-10-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0006_text_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='label',
            field=models.SlugField(max_length=128),
        ),
    ]
