# Generated by Django 2.2.5 on 2019-10-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0007_auto_20191026_0348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('corpus', 'label')},
        ),
    ]
