# Generated by Django 2.1.4 on 2019-10-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0008_auto_20191026_0354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadataentry',
            unique_together={('text', 'argument')},
        ),
    ]
