# Generated by Django 2.1.4 on 2019-10-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0009_auto_20191026_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='language',
            field=models.ForeignKey(on_delete='protect', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='metadataentry',
            name='argument',
            field=models.ForeignKey(on_delete='protect', to='corpora.MetaDataArgument'),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete='protect', to='corpora.Author'),
        ),
        migrations.AlterField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(on_delete='protect', to='corpora.Corpus'),
        ),
        migrations.AlterField(
            model_name='wdtext',
            name='concorso',
            field=models.ForeignKey(on_delete='protect', to='corpora.WDConcorso'),
        ),
        migrations.AlterField(
            model_name='wdtext',
            name='forum',
            field=models.ForeignKey(on_delete='protect', to='corpora.WDForum'),
        ),
    ]
