# Generated by Django 2.1.4 on 2019-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphabeticOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('order', models.CharField(default='AaÁáÀàÄäÆæ:Bb:CcÇç;Dd;EeÈèÉéËë;Ff;Gg;Hh;Ii;Jj;Kk;Ll;Mm;OoÒòÓóÖöŒœ;Pp;Qq;Rr;SsŞş;Tt;UuÙùÚúÜü;Vv;Ww;Xx;Yy;Zz', max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.CharField(max_length=10)),
                ('upper', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('pairs', models.ManyToManyField(blank=True, to='base.CasePair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenRegexp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('regexp', models.CharField(default='[a-zA-ZàèìòùáéíóúÀÈÌÒÙÁÉÍÓÚ]+', max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenRegexpSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenRegexpSetThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#ffff00', max_length=20)),
                ('fg_color', models.CharField(default='#000000', max_length=20)),
                ('order', models.IntegerField()),
                ('disabled', models.BooleanField()),
                ('token_regexp', models.ForeignKey(on_delete='cascade', to='base.TokenRegexp')),
                ('token_regexp_set', models.ForeignKey(on_delete='cascade', to='base.TokenRegexpSet')),
            ],
            options={
                'ordering': ['order', 'token_regexp_set'],
            },
        ),
        migrations.AddField(
            model_name='tokenregexpset',
            name='regexps',
            field=models.ManyToManyField(blank=True, through='base.TokenRegexpSetThrough', to='base.TokenRegexp'),
        ),
    ]
