# Generated by Django 2.1.4 on 2019-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphabeticOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('order', models.CharField(default='AaÁáÀàÄäÆæ;Bb;CcÇç;Dd;EeÈèÉéËë;Ff;Gg;Hh;Ii;Jj;Kk;Ll;Mm;OoÒòÓóÖöŒœ;Pp;Qq;Rr;SsŞş;Tt;UuÙùÚúÜü;Vv;Ww;Xx;Yy;Zz', max_length=2048)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CasePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.CharField(max_length=10)),
                ('upper', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('pairs', models.ManyToManyField(blank=True, to='base.CasePair')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invert', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete='protect', to='base.Attribute')),
            ],
            options={
                'ordering': ['attribute', 'value'],
            },
        ),
        migrations.CreateModel(
            name='TokenRegexp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('regexp', models.CharField(default='[a-zA-ZàèìòùáéíóúÀÈÌÒÙÁÉÍÓÚ]+', max_length=2048)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TokenRegexpSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TokenRegexpSetThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#ffff00', max_length=20)),
                ('fg_color', models.CharField(default='#000000', max_length=20)),
                ('order', models.IntegerField()),
                ('final', models.BooleanField(default=False)),
                ('disabled', models.BooleanField()),
                ('token_regexp', models.ForeignKey(on_delete='cascade', to='base.TokenRegexp')),
                ('token_regexp_set', models.ForeignKey(on_delete='cascade', to='base.TokenRegexpSet')),
            ],
            options={
                'ordering': ['order', 'token_regexp_set'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('variable', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tokenregexpset',
            name='regexps',
            field=models.ManyToManyField(blank=True, through='base.TokenRegexpSetThrough', to='base.TokenRegexp'),
        ),
        migrations.AddField(
            model_name='entry',
            name='value',
            field=models.ForeignKey(on_delete='protect', to='base.Value'),
        ),
        migrations.AddField(
            model_name='description',
            name='entries',
            field=models.ManyToManyField(blank=True, to='base.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('attribute', 'value', 'invert')},
        ),
    ]
