# Generated by Django 2.1.4 on 2019-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenregexpsetthrough',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
