# Generated by Django 2.1.4 on 2019-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('alphabetic_order', models.ForeignKey(on_delete='cascade', to='base.AlphabeticOrder')),
                ('case_set', models.ForeignKey(default=1, on_delete='cascade', to='base.CaseSet')),
                ('period_sep', models.ForeignKey(on_delete='cascade', to='base.TokenRegexp')),
                ('token_regexp_set', models.ForeignKey(on_delete='cascade', to='base.TokenRegexpSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('word', models.CharField(db_index=True, max_length=1024)),
                ('language', models.ForeignKey(on_delete='cascade', to='base.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
