# Generated by Django 2.1.4 on 2019-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_language_notword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabeticorder',
            name='order',
            field=models.CharField(default='AaÁáÀàÄäÆæ;Bb;CcÇç;Dd;EeÈèÉéËë;Ff;Gg;Hh;Ii;Jj;Kk;Ll;Mm;OoÒòÓóÖöŒœ;Pp;Qq;Rr;SsŞş;Tt;UuÙùÚúÜü;Vv;Ww;Xx;Yy;Zz', max_length=2048),
        ),
    ]
