# Generated by Django 2.1.4 on 2019-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190214_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negate', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete='cascade', to='base.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='SubDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete='cascade', to='base.Attribute')),
                ('value', models.ForeignKey(on_delete='cascade', to='base.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(db_index=True, max_length=1024)),
                ('variable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='value',
            field=models.ForeignKey(on_delete='cascade', to='base.Value'),
        ),
        migrations.AddField(
            model_name='description',
            name='entries',
            field=models.ManyToManyField(blank=True, to='base.Entry'),
        ),
        migrations.AddField(
            model_name='description',
            name='subdescriptions',
            field=models.ManyToManyField(blank=True, to='base.SubDescription'),
        ),
    ]
