# Generated by Django 2.1.4 on 2019-02-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190214_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='alphabetic_order',
        ),
        migrations.RemoveField(
            model_name='language',
            name='case_set',
        ),
        migrations.RemoveField(
            model_name='language',
            name='period_sep',
        ),
        migrations.RemoveField(
            model_name='language',
            name='token_regexp_set',
        ),
        migrations.RemoveField(
            model_name='notword',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='NotWord',
        ),
    ]
