# Generated by Django 2.1.4 on 2019-02-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190216_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['name']},
        ),
    ]
