# Generated by Django 2.1.2 on 2019-02-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
