# Generated by Django 2.1.4 on 2019-02-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['attribute', 'value']},
        ),
    ]
