# Generated by Django 2.2.5 on 2019-10-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190219_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenregexpsetthrough',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
