# Generated by Django 2.1.4 on 2019-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190219_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenregexp',
            name='invariant',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
