# Generated by Django 2.1.4 on 2019-10-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tokenregexpsetthrough_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alphabeticorder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='caseset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tokenregexp',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tokenregexpset',
            options={'ordering': ['name']},
        ),
    ]
