# Generated by Django 2.2.5 on 2019-10-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20191021_0713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('attribute', 'value', 'negate')},
        ),
    ]
