# Generated by Django 2.2.5 on 2019-10-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20191021_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='negate',
            new_name='invert',
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('attribute', 'value', 'invert')},
        ),
    ]
