# Generated by Django 2.1.4 on 2019-10-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20191026_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
