# Generated by Django 2.1.4 on 2019-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20191027_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='value',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
