# Generated by Django 2.1.4 on 2019-10-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20191027_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order']},
        ),
    ]
