# Generated by Django 2.1.4 on 2019-11-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20191027_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='subdescriptions',
        ),
    ]
