# Generated by Django 2.1.4 on 2019-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_description_subdescriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdescription',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='subdescription',
            name='value',
        ),
        migrations.DeleteModel(
            name='SubDescription',
        ),
    ]
